package protocol

// Code generated by github.com/tinylib/msgp DO NOT EDIT.

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *BulletMessage) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0001 uint32
	zb0001, err = dc.ReadArrayHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 9 {
		err = msgp.ArrayError{Wanted: 9, Got: zb0001}
		return
	}
	z.Magic, err = dc.ReadUint16()
	if err != nil {
		err = msgp.WrapError(err, "Magic")
		return
	}
	z.Version, err = dc.ReadUint8()
	if err != nil {
		err = msgp.WrapError(err, "Version")
		return
	}
	z.Type, err = dc.ReadUint8()
	if err != nil {
		err = msgp.WrapError(err, "Type")
		return
	}
	z.Timestamp, err = dc.ReadInt64()
	if err != nil {
		err = msgp.WrapError(err, "Timestamp")
		return
	}
	z.UserID, err = dc.ReadUint64()
	if err != nil {
		err = msgp.WrapError(err, "UserID")
		return
	}
	z.LiveID, err = dc.ReadUint64()
	if err != nil {
		err = msgp.WrapError(err, "LiveID")
		return
	}
	z.UserName, err = dc.ReadString()
	if err != nil {
		err = msgp.WrapError(err, "UserName")
		return
	}
	z.Content, err = dc.ReadString()
	if err != nil {
		err = msgp.WrapError(err, "Content")
		return
	}
	z.Color, err = dc.ReadString()
	if err != nil {
		err = msgp.WrapError(err, "Color")
		return
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *BulletMessage) EncodeMsg(en *msgp.Writer) (err error) {
	// array header, size 9
	err = en.Append(0x99)
	if err != nil {
		return
	}
	err = en.WriteUint16(z.Magic)
	if err != nil {
		err = msgp.WrapError(err, "Magic")
		return
	}
	err = en.WriteUint8(z.Version)
	if err != nil {
		err = msgp.WrapError(err, "Version")
		return
	}
	err = en.WriteUint8(z.Type)
	if err != nil {
		err = msgp.WrapError(err, "Type")
		return
	}
	err = en.WriteInt64(z.Timestamp)
	if err != nil {
		err = msgp.WrapError(err, "Timestamp")
		return
	}
	err = en.WriteUint64(z.UserID)
	if err != nil {
		err = msgp.WrapError(err, "UserID")
		return
	}
	err = en.WriteUint64(z.LiveID)
	if err != nil {
		err = msgp.WrapError(err, "LiveID")
		return
	}
	err = en.WriteString(z.UserName)
	if err != nil {
		err = msgp.WrapError(err, "UserName")
		return
	}
	err = en.WriteString(z.Content)
	if err != nil {
		err = msgp.WrapError(err, "Content")
		return
	}
	err = en.WriteString(z.Color)
	if err != nil {
		err = msgp.WrapError(err, "Color")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *BulletMessage) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// array header, size 9
	o = append(o, 0x99)
	o = msgp.AppendUint16(o, z.Magic)
	o = msgp.AppendUint8(o, z.Version)
	o = msgp.AppendUint8(o, z.Type)
	o = msgp.AppendInt64(o, z.Timestamp)
	o = msgp.AppendUint64(o, z.UserID)
	o = msgp.AppendUint64(o, z.LiveID)
	o = msgp.AppendString(o, z.UserName)
	o = msgp.AppendString(o, z.Content)
	o = msgp.AppendString(o, z.Color)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *BulletMessage) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadArrayHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if zb0001 != 9 {
		err = msgp.ArrayError{Wanted: 9, Got: zb0001}
		return
	}
	z.Magic, bts, err = msgp.ReadUint16Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "Magic")
		return
	}
	z.Version, bts, err = msgp.ReadUint8Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "Version")
		return
	}
	z.Type, bts, err = msgp.ReadUint8Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "Type")
		return
	}
	z.Timestamp, bts, err = msgp.ReadInt64Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "Timestamp")
		return
	}
	z.UserID, bts, err = msgp.ReadUint64Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "UserID")
		return
	}
	z.LiveID, bts, err = msgp.ReadUint64Bytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "LiveID")
		return
	}
	z.UserName, bts, err = msgp.ReadStringBytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "UserName")
		return
	}
	z.Content, bts, err = msgp.ReadStringBytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "Content")
		return
	}
	z.Color, bts, err = msgp.ReadStringBytes(bts)
	if err != nil {
		err = msgp.WrapError(err, "Color")
		return
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *BulletMessage) Msgsize() (s int) {
	s = 1 + msgp.Uint16Size + msgp.Uint8Size + msgp.Uint8Size + msgp.Int64Size + msgp.Uint64Size + msgp.Uint64Size + msgp.StringPrefixSize + len(z.UserName) + msgp.StringPrefixSize + len(z.Content) + msgp.StringPrefixSize + len(z.Color)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *SerializedBullet) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Timestamp":
			z.Timestamp, err = dc.ReadInt64()
			if err != nil {
				err = msgp.WrapError(err, "Timestamp")
				return
			}
		case "UserID":
			z.UserID, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "UserID")
				return
			}
		case "LiveID":
			z.LiveID, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "LiveID")
				return
			}
		case "UserName":
			z.UserName, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "UserName")
				return
			}
		case "Content":
			z.Content, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Content")
				return
			}
		case "Color":
			z.Color, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Color")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *SerializedBullet) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 6
	// write "Timestamp"
	err = en.Append(0x86, 0xa9, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70)
	if err != nil {
		return
	}
	err = en.WriteInt64(z.Timestamp)
	if err != nil {
		err = msgp.WrapError(err, "Timestamp")
		return
	}
	// write "UserID"
	err = en.Append(0xa6, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.UserID)
	if err != nil {
		err = msgp.WrapError(err, "UserID")
		return
	}
	// write "LiveID"
	err = en.Append(0xa6, 0x4c, 0x69, 0x76, 0x65, 0x49, 0x44)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.LiveID)
	if err != nil {
		err = msgp.WrapError(err, "LiveID")
		return
	}
	// write "UserName"
	err = en.Append(0xa8, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.UserName)
	if err != nil {
		err = msgp.WrapError(err, "UserName")
		return
	}
	// write "Content"
	err = en.Append(0xa7, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74)
	if err != nil {
		return
	}
	err = en.WriteString(z.Content)
	if err != nil {
		err = msgp.WrapError(err, "Content")
		return
	}
	// write "Color"
	err = en.Append(0xa5, 0x43, 0x6f, 0x6c, 0x6f, 0x72)
	if err != nil {
		return
	}
	err = en.WriteString(z.Color)
	if err != nil {
		err = msgp.WrapError(err, "Color")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *SerializedBullet) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 6
	// string "Timestamp"
	o = append(o, 0x86, 0xa9, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70)
	o = msgp.AppendInt64(o, z.Timestamp)
	// string "UserID"
	o = append(o, 0xa6, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44)
	o = msgp.AppendUint64(o, z.UserID)
	// string "LiveID"
	o = append(o, 0xa6, 0x4c, 0x69, 0x76, 0x65, 0x49, 0x44)
	o = msgp.AppendUint64(o, z.LiveID)
	// string "UserName"
	o = append(o, 0xa8, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65)
	o = msgp.AppendString(o, z.UserName)
	// string "Content"
	o = append(o, 0xa7, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74)
	o = msgp.AppendString(o, z.Content)
	// string "Color"
	o = append(o, 0xa5, 0x43, 0x6f, 0x6c, 0x6f, 0x72)
	o = msgp.AppendString(o, z.Color)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *SerializedBullet) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "Timestamp":
			z.Timestamp, bts, err = msgp.ReadInt64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Timestamp")
				return
			}
		case "UserID":
			z.UserID, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "UserID")
				return
			}
		case "LiveID":
			z.LiveID, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "LiveID")
				return
			}
		case "UserName":
			z.UserName, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "UserName")
				return
			}
		case "Content":
			z.Content, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Content")
				return
			}
		case "Color":
			z.Color, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Color")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *SerializedBullet) Msgsize() (s int) {
	s = 1 + 10 + msgp.Int64Size + 7 + msgp.Uint64Size + 7 + msgp.Uint64Size + 9 + msgp.StringPrefixSize + len(z.UserName) + 8 + msgp.StringPrefixSize + len(z.Content) + 6 + msgp.StringPrefixSize + len(z.Color)
	return
}
