type: client
logger:
  filePath: logs/edulive_client.log
  level: info
websocket:
  endpoint: "ws://127.0.0.1:8483/bullet"
distributor:
  quic:
    enabled: true
    addr: "127.0.0.1:8484"
    certFile: "test/ssl/cert.pem"
    keyFile: "test/ssl/key.pem"
client:
  liveID: 10000
  userID: 20003
  userName: "FriApr-01"
  sendInterval: 1500ms
  maxRetries: 3
  mode: "send"  # 客户端模式：send（发送弹幕）或 create（创建直播间）