type: client
logger:
  filePath: logs/edulive_client.log
  level: info
websocket:
  endpoint: "ws://localhost:8483/bullet"
distributor:
  quic:
    enabled: true
    addr: "localhost:8484"
    certFile: "data/cert.pem"
    keyFile: "data/key.pem"
client:
  liveID: 10000
  userID: 20003
  sendInterval: 1500ms
  maxRetries: 3
  mode: "create"  # 客户端模式：send（发送弹幕）或 create（创建直播间）