server:
  port: "8083"
logger:
  level: debug
  filepath: logs/edulive_server.log
websocket:
  enabled: true
  max_conns: 1000000
  idle_timeout: 5m
kafka:
  brokers:
    - "10.2.103.35:9092"
  topic: "bullet_topic"
redis:
  addr: "127.0.0.1:6379"
  password: "redis123"
  db: 0
distributor:
  quic:
    enabled: true
    addr: "127.0.0.1:443"
  cdn:
    enabled: true
    endpoint: "cdn.example.com"
observability:
  prometheus:
    enabled: true
    path: "/metrics"
  jaeger:
    enabled: true
    endpoint: "127.0.0.1:6831"
plugins:
  dir: "bin/plugins"
  enabled:
    - filter
    - rate_limit